### ISSUE TITLE
No tab created. 'Window' object has no attribute 'pointSize'

### ISSUE THREAD

**Issue by dyyybek** [carrois/Kernkraft#16]
Glyphs Version 2.5.2 (1161)
After hitting the "Open Tab" button:

```
Traceback (most recent call last):
  File "/Users/dyb/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1261, in LoadPreferences
    self.w.pointSize.set( self.Glyphs.defaults["%s.pointSize" % self.vID] )
AttributeError: 'Window' object has no attribute 'pointSize'

Could not load preferences. Will resort to defaults.
Traceback (most recent call last):
  File "/Users/dyb/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1334, in submitButtonCallback
    self.parent.generateTabOutput(actualInputGlyphName) # first main run
  File "/Users/dyb/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 911, in generateTabOutput
    self.makeTab(tabOutput)
  File "/Users/dyb/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 566, in makeTab
    self.UIPointSize = float(self.prefwindow.w.pointSize.get())
AttributeError: 'Window' object has no attribute 'pointSize'
```

**Comment by schriftgestalt** [comment]
This should not happen with the latest version. Can you open the Plugin Manager (or update it manually if you installed it manually)?
